Port: 8000

HTTP:
  Golinks:
    Enabled: true
    # Wiki: false

Log:
  Level: 6
  Stdout:
    Enabled: true
    WithColor: true

Metrics:
  SampleRate: 1
  Jaeger:
    Enabled: false
    # AgentEndpoint: localhost:6831
    # CollectorEndpoint: http://localhost:14268/api/traces

AuthProvider:
  Type: 'kv'
  Kv: &kv
    Type: 'bolt'
    LRUCache: true
    Bolt:
      Dir: 'datadir'
      Name: 'golinks.db'
    # LevelDB:
    #   Dir: datadir
    #   Name: golinks.db
    # Memory:
    #   Engine: map
    #   LRU:
    #     Cap: 1024

LinkStore:
  Type: 'kv'
  Kv: *kv
