name: docker-master
on:
  push:
    branches:
      - master
jobs:
  build-publish:
    name: publish docker image
    runs-on: ubuntu-latest
    steps:
      - name: login to docker hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - name: login to github container image registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - name: checkout
        uses: actions/checkout@master
      - run: git fetch --tags --unshallow
      - name: publish to docker hub with master tag
        run: DOCKER_TAG=master make docker docker-push
      - name: publish to github container image registry with master tag
        run: DOCKER_TAG=master DOCKER_REGISTRY=docker.pkg.github.com/haostudio/golinks make docker docker-push
